@EcoRide.Server_HostAddress = http://localhost:5276

GET {{EcoRide.Server_HostAddress}}/Itineraire/
Accept: application/json

###

GET {{EcoRide.Server_HostAddress}}/Covoiturage/
Accept: application/json

###

GET {{EcoRide.Server_HostAddress}}/Utilisateur/
Accept: application/json

###

GET {{EcoRide.Server_HostAddress}}/Profil/
Accept: application/json

###

GET {{EcoRide.Server_HostAddress}}/Authentification/
Accept: application/json

###

GET {{EcoRide.Server_HostAddress}}/Avis/
Accept: application/json

###