// <auto-generated />
using System;
using EcoRide.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EcoRide.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("EcoRide.Server.Covoiturage", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int?>("Id"));

                    b.Property<DateOnly>("DateArrivee")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DateDepart")
                        .HasColumnType("date");

                    b.Property<string>("LieuArrivee")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LieuDepart")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("NbPlace")
                        .HasColumnType("int");

                    b.Property<int>("PrixPersonne")
                        .HasColumnType("int");

                    b.Property<string>("Statut")
                        .HasColumnType("longtext");

                    b.Property<string>("heureArrivee")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<TimeOnly>("heureDepart")
                        .HasColumnType("time(6)");

                    b.HasKey("Id");

                    b.ToTable("covoiturage");
                });
#pragma warning restore 612, 618
        }
    }
}
